### ISSUE TITLE
How do I setup permalinks for a custom category helper?

### ISSUE THREAD

**Issue by grayghostvisuals** [assemble/assemble-permalinks#8]
Hi Jon and Brian,

I'm trying to setup permalinks in the following fashion…

```
sitename.com/{category,tag}/pagename.html
```

Currently I have a custom helper for categories that looks like so…

``` yml

---
basename: casestudy
title: Client Name
layout: default
categories: client

---
```

The docs are a bit light so I'm trying to decipher what the best approach is and the ones listed in the README don't work well for my case and result in errors. My entire setup can be seen here for reference on my [development branch](https://github.com/grayghostvisuals/site/tree/development)
